### ISSUE TITLE
Channel-wise pagename autocompletes to several channels

### ISSUE THREAD

**Issue by Skelpdar** [LDMX-Software/pflib#31]
**Describe the bug**
When writing to the page of a single digit channel, e.g. "Channel_1", it will also write to "Channel_10", "Channel_11" and so on. 

**To Reproduce**
Use the config:
```
Channel_1:
  Channel_off: 1
```
to see that that channels 10 to 19 are also turned off.

**Comment by tomeichlersmith** [comment]
This is due to the following lines

https://github.com/LDMX-Software/pflib/blob/2b21423f51c91ef79f8d1e62dbc507ce7daf4702/src/pflib/Compile.cxx#L593-L600

The simple solution to this is only do partial "globbing" matches when the user specifically provides the `*` character. Otherwise, require a full name match.
